---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 and php package for Debian Servers
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: remove apache2 and php package for Centos Servers
    package:
      name: 
        - httpd
        - php
      state: absent
      update_cache: yes
    when: ansible_distribution == "CentOS"

