---

- hosts: all
  become: true
  pre_tasks:
  - name: Install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install updates (Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:
  - name: install apache2 and php package for Debian Servers
    tags: apache,apache2,debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: install httpd and php package for Centos Servers
    dnf:
      name: 
      tags: centos,apache,apache2
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  - name: Install mariadb packacge (CentOS)
    tags: centos,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
  - name: Install mariadb packacge (Debian)
    tags: mariadb,debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:
  - name: install Samba package
    tags: samba
    package:
      name: samba
      state: latest

- hosts: docker
  become: true
  tasks:
  - name: Remove unwanted old packages
    tags: debian, docker
    apt:
      name:
        - docker.io
        - docker-doc
        - docker-compose
        - podman-docker
        - containerd
        - runc
      state: absent
    when: ansible_distribution == "Debian"
  - name: Install base Debian packages
    tags: debian,docker
    apt:
      name: 
        - nmon
        - vim
        - tree
        - mlocate
        - neofetch
        - ca-certificates
        - curl
        - gnupg
        - zabbix-agent2
      state: latest
    when: ansible_distribution == "Debian"

